### ISSUE TITLE
小説取得API作成

### ISSUE THREAD

**Issue by furutahidehiko** [furutahidehiko/mobile_reader_novel_back#1]

**Comment by watame** [comment]
PRはコレ
https://github.com/furutahidehiko/mobile_reader_novel_back/pull/2
- このPRでは本文取得処理のみを実施している
- 既読機能は未実装ですよ

**Comment by watame** [comment]
Notionの考慮事項です
https://www.notion.so/API-3c4d100f687f4cc98f6dcbeadc3a8bad?pvs=4#066858a495dc44fbb5cfb906e65a5f2f
